<?php

class Maera_MD_Data {

	public static function colors() {

		$colors = array(
			0        => array( 'label' => '', 'classes' => '' ),
			'ffebee' => array( 'label' => 'red lighten-5', 'classes' => 'red lighten-5' ),
			'ffcdd2' => array( 'label' => 'red lighten-4', 'classes' => 'red lighten-4' ),
			'e57373' => array( 'label' => 'red lighten-3', 'classes' => 'red lighten-3' ),
			'ef9a9a' => array( 'label' => 'red lighten-2', 'classes' => 'red lighten-2' ),
			'ef5350' => array( 'label' => 'red lighten-1', 'classes' => 'red lighten-1' ),
			'f44336' => array( 'label' => 'red', 'classes' => 'red' ),
			'e53935' => array( 'label' => 'red darken-1', 'classes' => 'red darken-1' ),
			'd32f2f' => array( 'label' => 'red darken-2', 'classes' => 'red darken-2' ),
			'c62828' => array( 'label' => 'red darken-3', 'classes' => 'red darken-3' ),
			'b71c1c' => array( 'label' => 'red darken-4', 'classes' => 'red darken-4' ),
			'ff8a80' => array( 'label' => 'red accent-1', 'classes' => 'red accent-1' ),
			'ff5252' => array( 'label' => 'red accent-2', 'classes' => 'red accent-2' ),
			'ff1744' => array( 'label' => 'red accent-3', 'classes' => 'red accent-3' ),
			'd50000' => array( 'label' => 'red accent-4', 'classes' => 'red accent-4' ),
			'fce4ec' => array( 'label' => 'pink lighten-5', 'classes' => 'pink lighten-5' ),
			'f8bbd0' => array( 'label' => 'pink lighten-4', 'classes' => 'pink lighten-4' ),
			'f06292' => array( 'label' => 'pink lighten-3', 'classes' => 'pink lighten-3' ),
			'f48fb1' => array( 'label' => 'pink lighten-2', 'classes' => 'pink lighten-2' ),
			'ec407a' => array( 'label' => 'pink lighten-1', 'classes' => 'pink lighten-1' ),
			'e91e63' => array( 'label' => 'pink', 'classes' => 'pink' ),
			'd81b60' => array( 'label' => 'pink darken-1', 'classes' => 'pink darken-1' ),
			'c2185b' => array( 'label' => 'pink darken-2', 'classes' => 'pink darken-2' ),
			'ad1457' => array( 'label' => 'pink darken-3', 'classes' => 'pink darken-3' ),
			'880e4f' => array( 'label' => 'pink darken-4', 'classes' => 'pink darken-4' ),
			'ff80ab' => array( 'label' => 'pink accent-1', 'classes' => 'pink accent-1' ),
			'ff4081' => array( 'label' => 'pink accent-2', 'classes' => 'pink accent-2' ),
			'f50057' => array( 'label' => 'pink accent-3', 'classes' => 'pink accent-3' ),
			'c51162' => array( 'label' => 'pink accent-4', 'classes' => 'pink accent-4' ),
			'f3e5f5' => array( 'label' => 'purple lighten-5', 'classes' => 'purple lighten-5' ),
			'e1bee7' => array( 'label' => 'purple lighten-4', 'classes' => 'purple lighten-4' ),
			'ba68c8' => array( 'label' => 'purple lighten-3', 'classes' => 'purple lighten-3' ),
			'ce93d8' => array( 'label' => 'purple lighten-2', 'classes' => 'purple lighten-2' ),
			'ab47bc' => array( 'label' => 'purple lighten-1', 'classes' => 'purple lighten-1' ),
			'9c27b0' => array( 'label' => 'purple', 'classes' => 'purple' ),
			'8e24aa' => array( 'label' => 'purple darken-1', 'classes' => 'purple darken-1' ),
			'7b1fa2' => array( 'label' => 'purple darken-2', 'classes' => 'purple darken-2' ),
			'6a1b9a' => array( 'label' => 'purple darken-3', 'classes' => 'purple darken-3' ),
			'4a148c' => array( 'label' => 'purple darken-4', 'classes' => 'purple darken-4' ),
			'ea80fc' => array( 'label' => 'purple accent-1', 'classes' => 'purple accent-1' ),
			'e040fb' => array( 'label' => 'purple accent-2', 'classes' => 'purple accent-2' ),
			'd500f9' => array( 'label' => 'purple accent-3', 'classes' => 'purple accent-3' ),
			'aa00ff' => array( 'label' => 'purple accent-4', 'classes' => 'purple accent-4' ),
			'ede7f6' => array( 'label' => 'deep-purple lighten-5', 'classes' => 'deep-purple lighten-5' ),
			'd1c4e9' => array( 'label' => 'deep-purple lighten-4', 'classes' => 'deep-purple lighten-4' ),
			'9575cd' => array( 'label' => 'deep-purple lighten-3', 'classes' => 'deep-purple lighten-3' ),
			'b39ddb' => array( 'label' => 'deep-purple lighten-2', 'classes' => 'deep-purple lighten-2' ),
			'7e57c2' => array( 'label' => 'deep-purple lighten-1', 'classes' => 'deep-purple lighten-1' ),
			'673ab7' => array( 'label' => 'deep-purple', 'classes' => 'deep-purple' ),
			'5e35b1' => array( 'label' => 'deep-purple darken-1', 'classes' => 'deep-purple darken-1' ),
			'512da8' => array( 'label' => 'deep-purple darken-2', 'classes' => 'deep-purple darken-2' ),
			'4527a0' => array( 'label' => 'deep-purple darken-3', 'classes' => 'deep-purple darken-3' ),
			'311b92' => array( 'label' => 'deep-purple darken-4', 'classes' => 'deep-purple darken-4' ),
			'b388ff' => array( 'label' => 'deep-purple accent-1', 'classes' => 'deep-purple accent-1' ),
			'7c4dff' => array( 'label' => 'deep-purple accent-2', 'classes' => 'deep-purple accent-2' ),
			'651fff' => array( 'label' => 'deep-purple accent-3', 'classes' => 'deep-purple accent-3' ),
			'6200ea' => array( 'label' => 'deep-purple accent-4', 'classes' => 'deep-purple accent-4' ),
			'e8eaf6' => array( 'label' => 'indigo lighten-5', 'classes' => 'indigo lighten-5' ),
			'c5cae9' => array( 'label' => 'indigo lighten-4', 'classes' => 'indigo lighten-4' ),
			'7986cb' => array( 'label' => 'indigo lighten-3', 'classes' => 'indigo lighten-3' ),
			'9fa8da' => array( 'label' => 'indigo lighten-2', 'classes' => 'indigo lighten-2' ),
			'5c6bc0' => array( 'label' => 'indigo lighten-1', 'classes' => 'indigo lighten-1' ),
			'3f51b5' => array( 'label' => 'indigo', 'classes' => 'indigo' ),
			'3949ab' => array( 'label' => 'indigo darken-1', 'classes' => 'indigo darken-1' ),
			'303f9f' => array( 'label' => 'indigo darken-2', 'classes' => 'indigo darken-2' ),
			'283593' => array( 'label' => 'indigo darken-3', 'classes' => 'indigo darken-3' ),
			'1a237e' => array( 'label' => 'indigo darken-4', 'classes' => 'indigo darken-4' ),
			'8c9eff' => array( 'label' => 'indigo accent-1', 'classes' => 'indigo accent-1' ),
			'536dfe' => array( 'label' => 'indigo accent-2', 'classes' => 'indigo accent-2' ),
			'3d5afe' => array( 'label' => 'indigo accent-3', 'classes' => 'indigo accent-3' ),
			'304ffe' => array( 'label' => 'indigo accent-4', 'classes' => 'indigo accent-4' ),
			'e3f2fd' => array( 'label' => 'blue lighten-5', 'classes' => 'blue lighten-5' ),
			'bbdefb' => array( 'label' => 'blue lighten-4', 'classes' => 'blue lighten-4' ),
			'64b5f6' => array( 'label' => 'blue lighten-3', 'classes' => 'blue lighten-3' ),
			'90caf9' => array( 'label' => 'blue lighten-2', 'classes' => 'blue lighten-2' ),
			'42a5f5' => array( 'label' => 'blue lighten-1', 'classes' => 'blue lighten-1' ),
			'2196f3' => array( 'label' => 'blue', 'classes' => 'blue' ),
			'1e88e5' => array( 'label' => 'blue darken-1', 'classes' => 'blue darken-1' ),
			'1976d2' => array( 'label' => 'blue darken-2', 'classes' => 'blue darken-2' ),
			'1565c0' => array( 'label' => 'blue darken-3', 'classes' => 'blue darken-3' ),
			'0d47a1' => array( 'label' => 'blue darken-4', 'classes' => 'blue darken-4' ),
			'82b1ff' => array( 'label' => 'blue accent-1', 'classes' => 'blue accent-1' ),
			'448aff' => array( 'label' => 'blue accent-2', 'classes' => 'blue accent-2' ),
			'2979ff' => array( 'label' => 'blue accent-3', 'classes' => 'blue accent-3' ),
			'2962ff' => array( 'label' => 'blue accent-4', 'classes' => 'blue accent-4' ),
			'e1f5fe' => array( 'label' => 'light-blue lighten-5', 'classes' => 'light-blue lighten-5' ),
			'b3e5fc' => array( 'label' => 'light-blue lighten-4', 'classes' => 'light-blue lighten-4' ),
			'4fc3f7' => array( 'label' => 'light-blue lighten-3', 'classes' => 'light-blue lighten-3' ),
			'81d4fa' => array( 'label' => 'light-blue lighten-2', 'classes' => 'light-blue lighten-2' ),
			'29b6f6' => array( 'label' => 'light-blue lighten-1', 'classes' => 'light-blue lighten-1' ),
			'03a9f4' => array( 'label' => 'light-blue', 'classes' => 'light-blue' ),
			'039be5' => array( 'label' => 'light-blue darken-1', 'classes' => 'light-blue darken-1' ),
			'0288d1' => array( 'label' => 'light-blue darken-2', 'classes' => 'light-blue darken-2' ),
			'0277bd' => array( 'label' => 'light-blue darken-3', 'classes' => 'light-blue darken-3' ),
			'01579b' => array( 'label' => 'light-blue darken-4', 'classes' => 'light-blue darken-4' ),
			'80d8ff' => array( 'label' => 'light-blue accent-1', 'classes' => 'light-blue accent-1' ),
			'40c4ff' => array( 'label' => 'light-blue accent-2', 'classes' => 'light-blue accent-2' ),
			'00b0ff' => array( 'label' => 'light-blue accent-3', 'classes' => 'light-blue accent-3' ),
			'0091ea' => array( 'label' => 'light-blue accent-4', 'classes' => 'light-blue accent-4' ),
			'e0f7fa' => array( 'label' => 'cyan lighten-5', 'classes' => 'cyan lighten-5' ),
			'b2ebf2' => array( 'label' => 'cyan lighten-4', 'classes' => 'cyan lighten-4' ),
			'4dd0e1' => array( 'label' => 'cyan lighten-3', 'classes' => 'cyan lighten-3' ),
			'80deea' => array( 'label' => 'cyan lighten-2', 'classes' => 'cyan lighten-2' ),
			'26c6da' => array( 'label' => 'cyan lighten-1', 'classes' => 'cyan lighten-1' ),
			'00bcd4' => array( 'label' => 'cyan', 'classes' => 'cyan' ),
			'00acc1' => array( 'label' => 'cyan darken-1', 'classes' => 'cyan darken-1' ),
			'0097a7' => array( 'label' => 'cyan darken-2', 'classes' => 'cyan darken-2' ),
			'00838f' => array( 'label' => 'cyan darken-3', 'classes' => 'cyan darken-3' ),
			'006064' => array( 'label' => 'cyan darken-4', 'classes' => 'cyan darken-4' ),
			'84ffff' => array( 'label' => 'cyan accent-1', 'classes' => 'cyan accent-1' ),
			'18ffff' => array( 'label' => 'cyan accent-2', 'classes' => 'cyan accent-2' ),
			'00e5ff' => array( 'label' => 'cyan accent-3', 'classes' => 'cyan accent-3' ),
			'00b8d4' => array( 'label' => 'cyan accent-4', 'classes' => 'cyan accent-4' ),
			'e0f2f1' => array( 'label' => 'teal lighten-5', 'classes' => 'teal lighten-5' ),
			'b2dfdb' => array( 'label' => 'teal lighten-4', 'classes' => 'teal lighten-4' ),
			'4db6ac' => array( 'label' => 'teal lighten-3', 'classes' => 'teal lighten-3' ),
			'80cbc4' => array( 'label' => 'teal lighten-2', 'classes' => 'teal lighten-2' ),
			'26a69a' => array( 'label' => 'teal lighten-1', 'classes' => 'teal lighten-1' ),
			'009688' => array( 'label' => 'teal', 'classes' => 'teal' ),
			'00897b' => array( 'label' => 'teal darken-1', 'classes' => 'teal darken-1' ),
			'00796b' => array( 'label' => 'teal darken-2', 'classes' => 'teal darken-2' ),
			'00695c' => array( 'label' => 'teal darken-3', 'classes' => 'teal darken-3' ),
			'004d40' => array( 'label' => 'teal darken-4', 'classes' => 'teal darken-4' ),
			'a7ffeb' => array( 'label' => 'teal accent-1', 'classes' => 'teal accent-1' ),
			'64ffda' => array( 'label' => 'teal accent-2', 'classes' => 'teal accent-2' ),
			'1de9b6' => array( 'label' => 'teal accent-3', 'classes' => 'teal accent-3' ),
			'00bfa5' => array( 'label' => 'teal accent-4', 'classes' => 'teal accent-4' ),
			'e8f5e9' => array( 'label' => 'green lighten-5', 'classes' => 'green lighten-5' ),
			'c8e6c9' => array( 'label' => 'green lighten-4', 'classes' => 'green lighten-4' ),
			'81c784' => array( 'label' => 'green lighten-3', 'classes' => 'green lighten-3' ),
			'a5d6a7' => array( 'label' => 'green lighten-2', 'classes' => 'green lighten-2' ),
			'66bb6a' => array( 'label' => 'green lighten-1', 'classes' => 'green lighten-1' ),
			'4caf50' => array( 'label' => 'green', 'classes' => 'green' ),
			'43a047' => array( 'label' => 'green darken-1', 'classes' => 'green darken-1' ),
			'388e3c' => array( 'label' => 'green darken-2', 'classes' => 'green darken-2' ),
			'2e7d32' => array( 'label' => 'green darken-3', 'classes' => 'green darken-3' ),
			'1b5e20' => array( 'label' => 'green darken-4', 'classes' => 'green darken-4' ),
			'b9f6ca' => array( 'label' => 'green accent-1', 'classes' => 'green accent-1' ),
			'69f0ae' => array( 'label' => 'green accent-2', 'classes' => 'green accent-2' ),
			'00e676' => array( 'label' => 'green accent-3', 'classes' => 'green accent-3' ),
			'00c853' => array( 'label' => 'green accent-4', 'classes' => 'green accent-4' ),
			'f1f8e9' => array( 'label' => 'light-green lighten-5', 'classes' => 'light-green lighten-5' ),
			'dcedc8' => array( 'label' => 'light-green lighten-4', 'classes' => 'light-green lighten-4' ),
			'aed581' => array( 'label' => 'light-green lighten-3', 'classes' => 'light-green lighten-3' ),
			'c5e1a5' => array( 'label' => 'light-green lighten-2', 'classes' => 'light-green lighten-2' ),
			'9ccc65' => array( 'label' => 'light-green lighten-1', 'classes' => 'light-green lighten-1' ),
			'8bc34a' => array( 'label' => 'light-green', 'classes' => 'light-green' ),
			'7cb342' => array( 'label' => 'light-green darken-1', 'classes' => 'light-green darken-1' ),
			'689f38' => array( 'label' => 'light-green darken-2', 'classes' => 'light-green darken-2' ),
			'558b2f' => array( 'label' => 'light-green darken-3', 'classes' => 'light-green darken-3' ),
			'33691e' => array( 'label' => 'light-green darken-4', 'classes' => 'light-green darken-4' ),
			'ccff90' => array( 'label' => 'light-green accent-1', 'classes' => 'light-green accent-1' ),
			'b2ff59' => array( 'label' => 'light-green accent-2', 'classes' => 'light-green accent-2' ),
			'76ff03' => array( 'label' => 'light-green accent-3', 'classes' => 'light-green accent-3' ),
			'64dd17' => array( 'label' => 'light-green accent-4', 'classes' => 'light-green accent-4' ),
			'f9fbe7' => array( 'label' => 'lime lighten-5', 'classes' => 'lime lighten-5' ),
			'f0f4c3' => array( 'label' => 'lime lighten-4', 'classes' => 'lime lighten-4' ),
			'dce775' => array( 'label' => 'lime lighten-3', 'classes' => 'lime lighten-3' ),
			'e6ee9c' => array( 'label' => 'lime lighten-2', 'classes' => 'lime lighten-2' ),
			'd4e157' => array( 'label' => 'lime lighten-1', 'classes' => 'lime lighten-1' ),
			'cddc39' => array( 'label' => 'lime', 'classes' => 'lime' ),
			'c0ca33' => array( 'label' => 'lime darken-1', 'classes' => 'lime darken-1' ),
			'afb42b' => array( 'label' => 'lime darken-2', 'classes' => 'lime darken-2' ),
			'9e9d24' => array( 'label' => 'lime darken-3', 'classes' => 'lime darken-3' ),
			'827717' => array( 'label' => 'lime darken-4', 'classes' => 'lime darken-4' ),
			'f4ff81' => array( 'label' => 'lime accent-1', 'classes' => 'lime accent-1' ),
			'eeff41' => array( 'label' => 'lime accent-2', 'classes' => 'lime accent-2' ),
			'c6ff00' => array( 'label' => 'lime accent-3', 'classes' => 'lime accent-3' ),
			'aeea00' => array( 'label' => 'lime accent-4', 'classes' => 'lime accent-4' ),
			'fffde7' => array( 'label' => 'yellow lighten-5', 'classes' => 'yellow lighten-5' ),
			'fff9c4' => array( 'label' => 'yellow lighten-4', 'classes' => 'yellow lighten-4' ),
			'fff176' => array( 'label' => 'yellow lighten-3', 'classes' => 'yellow lighten-3' ),
			'fff59d' => array( 'label' => 'yellow lighten-2', 'classes' => 'yellow lighten-2' ),
			'ffee58' => array( 'label' => 'yellow lighten-1', 'classes' => 'yellow lighten-1' ),
			'ffeb3b' => array( 'label' => 'yellow', 'classes' => 'yellow' ),
			'fdd835' => array( 'label' => 'yellow darken-1', 'classes' => 'yellow darken-1' ),
			'fbc02d' => array( 'label' => 'yellow darken-2', 'classes' => 'yellow darken-2' ),
			'f9a825' => array( 'label' => 'yellow darken-3', 'classes' => 'yellow darken-3' ),
			'f57f17' => array( 'label' => 'yellow darken-4', 'classes' => 'yellow darken-4' ),
			'ffff8d' => array( 'label' => 'yellow accent-1', 'classes' => 'yellow accent-1' ),
			'ffff00' => array( 'label' => 'yellow accent-2', 'classes' => 'yellow accent-2' ),
			'ffea00' => array( 'label' => 'yellow accent-3', 'classes' => 'yellow accent-3' ),
			'ffd600' => array( 'label' => 'yellow accent-4', 'classes' => 'yellow accent-4' ),
			'fff8e1' => array( 'label' => 'amber lighten-5', 'classes' => 'amber lighten-5' ),
			'ffecb3' => array( 'label' => 'amber lighten-4', 'classes' => 'amber lighten-4' ),
			'ffd54f' => array( 'label' => 'amber lighten-3', 'classes' => 'amber lighten-3' ),
			'ffe082' => array( 'label' => 'amber lighten-2', 'classes' => 'amber lighten-2' ),
			'ffca28' => array( 'label' => 'amber lighten-1', 'classes' => 'amber lighten-1' ),
			'ffc107' => array( 'label' => 'amber', 'classes' => 'amber' ),
			'ffb300' => array( 'label' => 'amber darken-1', 'classes' => 'amber darken-1' ),
			'ffa000' => array( 'label' => 'amber darken-2', 'classes' => 'amber darken-2' ),
			'ff8f00' => array( 'label' => 'amber darken-3', 'classes' => 'amber darken-3' ),
			'ff6f00' => array( 'label' => 'amber darken-4', 'classes' => 'amber darken-4' ),
			'ffe57f' => array( 'label' => 'amber accent-1', 'classes' => 'amber accent-1' ),
			'ffd740' => array( 'label' => 'amber accent-2', 'classes' => 'amber accent-2' ),
			'ffc400' => array( 'label' => 'amber accent-3', 'classes' => 'amber accent-3' ),
			'ffab00' => array( 'label' => 'amber accent-4', 'classes' => 'amber accent-4' ),
			'fff3e0' => array( 'label' => 'orange lighten-5', 'classes' => 'orange lighten-5' ),
			'ffe0b2' => array( 'label' => 'orange lighten-4', 'classes' => 'orange lighten-4' ),
			'ffb74d' => array( 'label' => 'orange lighten-3', 'classes' => 'orange lighten-3' ),
			'ffcc80' => array( 'label' => 'orange lighten-2', 'classes' => 'orange lighten-2' ),
			'ffa726' => array( 'label' => 'orange lighten-1', 'classes' => 'orange lighten-1' ),
			'ff9800' => array( 'label' => 'orange', 'classes' => 'orange' ),
			'fb8c00' => array( 'label' => 'orange darken-1', 'classes' => 'orange darken-1' ),
			'f57c00' => array( 'label' => 'orange darken-2', 'classes' => 'orange darken-2' ),
			'ef6c00' => array( 'label' => 'orange darken-3', 'classes' => 'orange darken-3' ),
			'e65100' => array( 'label' => 'orange darken-4', 'classes' => 'orange darken-4' ),
			'ffd180' => array( 'label' => 'orange accent-1', 'classes' => 'orange accent-1' ),
			'ffab40' => array( 'label' => 'orange accent-2', 'classes' => 'orange accent-2' ),
			'ff9100' => array( 'label' => 'orange accent-3', 'classes' => 'orange accent-3' ),
			'ff6d00' => array( 'label' => 'orange accent-4', 'classes' => 'orange accent-4' ),
			'fbe9e7' => array( 'label' => 'deep-orange lighten-5', 'classes' => 'deep-orange lighten-5' ),
			'ffccbc' => array( 'label' => 'deep-orange lighten-4', 'classes' => 'deep-orange lighten-4' ),
			'ff8a65' => array( 'label' => 'deep-orange lighten-3', 'classes' => 'deep-orange lighten-3' ),
			'ffab91' => array( 'label' => 'deep-orange lighten-2', 'classes' => 'deep-orange lighten-2' ),
			'ff7043' => array( 'label' => 'deep-orange lighten-1', 'classes' => 'deep-orange lighten-1' ),
			'ff5722' => array( 'label' => 'deep-orange', 'classes' => 'deep-orange' ),
			'f4511e' => array( 'label' => 'deep-orange darken-1', 'classes' => 'deep-orange darken-1' ),
			'e64a19' => array( 'label' => 'deep-orange darken-2', 'classes' => 'deep-orange darken-2' ),
			'd84315' => array( 'label' => 'deep-orange darken-3', 'classes' => 'deep-orange darken-3' ),
			'bf360c' => array( 'label' => 'deep-orange darken-4', 'classes' => 'deep-orange darken-4' ),
			'ff9e80' => array( 'label' => 'deep-orange accent-1', 'classes' => 'deep-orange accent-1' ),
			'ff6e40' => array( 'label' => 'deep-orange accent-2', 'classes' => 'deep-orange accent-2' ),
			'ff3d00' => array( 'label' => 'deep-orange accent-3', 'classes' => 'deep-orange accent-3' ),
			'dd2c00' => array( 'label' => 'deep-orange accent-4', 'classes' => 'deep-orange accent-4' ),
			'efebe9' => array( 'label' => 'brown lighten-5', 'classes' => 'brown lighten-5' ),
			'd7ccc8' => array( 'label' => 'brown lighten-4', 'classes' => 'brown lighten-4' ),
			'a1887f' => array( 'label' => 'brown lighten-3', 'classes' => 'brown lighten-3' ),
			'bcaaa4' => array( 'label' => 'brown lighten-2', 'classes' => 'brown lighten-2' ),
			'8d6e63' => array( 'label' => 'brown lighten-1', 'classes' => 'brown lighten-1' ),
			'795548' => array( 'label' => 'brown', 'classes' => 'brown' ),
			'6d4c41' => array( 'label' => 'brown darken-1', 'classes' => 'brown darken-1' ),
			'5d4037' => array( 'label' => 'brown darken-2', 'classes' => 'brown darken-2' ),
			'4e342e' => array( 'label' => 'brown darken-3', 'classes' => 'brown darken-3' ),
			'3e2723' => array( 'label' => 'brown darken-4', 'classes' => 'brown darken-4' ),
			'fafafa' => array( 'label' => 'grey lighten-5', 'classes' => 'grey lighten-5' ),
			'f5f5f5' => array( 'label' => 'grey lighten-4', 'classes' => 'grey lighten-4' ),
			'e0e0e0' => array( 'label' => 'grey lighten-3', 'classes' => 'grey lighten-3' ),
			'eeeeee' => array( 'label' => 'grey lighten-2', 'classes' => 'grey lighten-2' ),
			'bdbdbd' => array( 'label' => 'grey lighten-1', 'classes' => 'grey lighten-1' ),
			'9e9e9e' => array( 'label' => 'grey', 'classes' => 'grey' ),
			'757575' => array( 'label' => 'grey darken-1', 'classes' => 'grey darken-1' ),
			'616161' => array( 'label' => 'grey darken-2', 'classes' => 'grey darken-2' ),
			'424242' => array( 'label' => 'grey darken-3', 'classes' => 'grey darken-3' ),
			'212121' => array( 'label' => 'grey darken-4', 'classes' => 'grey darken-4' ),
			'eceff1' => array( 'label' => 'blue-grey lighten-5', 'classes' => 'blue-grey lighten-5' ),
			'cfd8dc' => array( 'label' => 'blue-grey lighten-4', 'classes' => 'blue-grey lighten-4' ),
			'90a4ae' => array( 'label' => 'blue-grey lighten-3', 'classes' => 'blue-grey lighten-3' ),
			'b0bec5' => array( 'label' => 'blue-grey lighten-2', 'classes' => 'blue-grey lighten-2' ),
			'78909c' => array( 'label' => 'blue-grey lighten-1', 'classes' => 'blue-grey lighten-1' ),
			'607d8b' => array( 'label' => 'blue-grey', 'classes' => 'blue-grey' ),
			'546e7a' => array( 'label' => 'blue-grey darken-1', 'classes' => 'blue-grey darken-1' ),
			'455a64' => array( 'label' => 'blue-grey darken-2', 'classes' => 'blue-grey darken-2' ),
			'37474f' => array( 'label' => 'blue-grey darken-3', 'classes' => 'blue-grey darken-3' ),
			'263238' => array( 'label' => 'blue-grey darken-4', 'classes' => 'blue-grey darken-4' ),
		);

		return $colors;

	}

	public static function main_colors() {

		$colors = array(
			'f44336' => array( 'label' => 'red', 'classes' => 'red' ),
			'e91e63' => array( 'label' => 'pink', 'classes' => 'pink' ),
			'9c27b0' => array( 'label' => 'purple', 'classes' => 'purple' ),
			'673ab7' => array( 'label' => 'deep-purple', 'classes' => 'deep-purple' ),
			'3f51b5' => array( 'label' => 'indigo', 'classes' => 'indigo' ),
			'2196f3' => array( 'label' => 'blue', 'classes' => 'blue' ),
			'03a9f4' => array( 'label' => 'light-blue', 'classes' => 'light-blue' ),
			'00bcd4' => array( 'label' => 'cyan', 'classes' => 'cyan' ),
			'009688' => array( 'label' => 'teal', 'classes' => 'teal' ),
			'4caf50' => array( 'label' => 'green', 'classes' => 'green' ),
			'8bc34a' => array( 'label' => 'light-green', 'classes' => 'light-green' ),
			'cddc39' => array( 'label' => 'lime', 'classes' => 'lime' ),
			'ffeb3b' => array( 'label' => 'yellow', 'classes' => 'yellow' ),
			'ffc107' => array( 'label' => 'amber', 'classes' => 'amber' ),
			'ff9800' => array( 'label' => 'orange', 'classes' => 'orange' ),
			'ff5722' => array( 'label' => 'deep-orange', 'classes' => 'deep-orange' ),
			'795548' => array( 'label' => 'brown', 'classes' => 'brown' ),
			'9e9e9e' => array( 'label' => 'grey', 'classes' => 'grey' ),
			'607d8b' => array( 'label' => 'blue-grey', 'classes' => 'blue-grey' ),
		);

		return $colors;

	}

	public static function depths() {

		$depths = array(
			1 => array( 'label' => 'z-depth-1', 'classes' => 'z-depth-1' ),
			2 => array( 'label' => 'z-depth-2', 'classes' => 'z-depth-2' ),
			3 => array( 'label' => 'z-depth-3', 'classes' => 'z-depth-3' ),
			4 => array( 'label' => 'z-depth-4', 'classes' => 'z-depth-4' ),
			5 => array( 'label' => 'z-depth-5', 'classes' => 'z-depth-5' ),
		);

		return $depths;

	}

	public static function widths() {

		$depths = array(
			12 => array( 'label' => 'Full', 'classes' => 'col s12' ),
			1  => array( 'label' => '1/12', 'classes' => 'col s12 m12 l1' ),
			2  => array( 'label' => '2/12', 'classes' => 'col s12 m12 l2' ),
			3  => array( 'label' => '3/12', 'classes' => 'col s12 m12 l3' ),
			4  => array( 'label' => '4/12', 'classes' => 'col s12 m12 l4' ),
			5  => array( 'label' => '5/12', 'classes' => 'col s12 m12 l5' ),
			6  => array( 'label' => '6/12', 'classes' => 'col s12 m12 l6' ),
			7  => array( 'label' => '7/12', 'classes' => 'col s12 m12 l7' ),
			8  => array( 'label' => '8/12', 'classes' => 'col s12 m12 l8' ),
			9  => array( 'label' => '9/12', 'classes' => 'col s12 m12 l9' ),
			10 => array( 'label' => '10/12', 'classes' => 'col s12 m12 l10' ),
			11 => array( 'label' => '11/12', 'classes' => 'col s12 m12 l11' ),
		);

		return $depths;

	}

	public static function simple_colors() {

		$colors = Maera_MD_Data::colors();
		$simple_colors = array();

		foreach ( $colors as $color => $values ) {
			$simple_colors[$color] = $values['label'];
		}

		return $simple_colors;

	}

	public static function simple_main_colors( $only_labels = false ) {

		$colors = Maera_MD_Data::main_colors();
		$simple_colors = array();

		foreach ( $colors as $color => $values ) {
			if ( $only_labels ) {
				$simple_colors[$values['label']] = $values['label'];
			} else {
				$simple_colors[$color] = $values['label'];
			}
		}

		return $simple_colors;

	}

}
